site_name: W4M Documentation test
theme:
 name: material
 logo: https://avatars.githubusercontent.com/u/17082156?s=200&v=4
 favicon: https://avatars.githubusercontent.com/u/17082156?s=200&v=4
 features:
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.expand
  - navigation.path

nav:
 - Introduction: index.md
 - SectionA:
  - partie 1: sectionA/page1.md
  - partie 2: sectionA/page2.md
  - partie 3: sectionA/page3.md
